spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cctower?useUnicode=true&characterEncoding=UTF8
    username: root
    password: Cctower0000*
  redis:
    host: 47.93.13.31
    port: 6379
    password: Cctower0000*
    timeout: 1000
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 100
        max-wait: -1
  rabbitmq:
    host: 47.93.13.31
    port: 5672
    username: cctower
    password: Cctower00000*
  activemq:
    broker-url: tcp://47.93.13.31:61616
    user: cctower
    password: Cctower00000*
  jms:
    pub-sub-domain: false     #false=Queue  true=Topic
# wx相关信息
wx:
  app-id: wx84582d8d20ac4deb
  app-secret: b25600a51d090381e02dd4b543955641
  mch-id: 1527166311
  mch-key: MQF82fY2pbWJOvGutpa7yHaK5pSgbAPK
  notify-url: https://www.cctower.cn/applet/wx-pay/pay-notify
  key-path: /usr/local/cctower/1527166311_20190406_cert/

pay:
  alipay:
    gatewayUrl: https://openapi.alipay.com/gateway.do
    appid: 2021001101693604
    appPrivateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQChbG8TAhF9Cyj7gfesEpVdv9FuLgYfjhJ4m7FUUHca+S0RGWDMSk0jvshlks2w0hXJfoDqZg0ZiD/1eEjy138qEVByy7/RmxVOgeN7/q3Q83tFsGHD6QJpi99zlqxmCml4NINrAIgXYdF3hQaYq7x6LTH9GWiFsXYHLxLiTdca605NsnmZf3rsVBDNg1CBHNxIXUWs40u2r72lvTREzx25UHIZqGufm70m2O7qG//0ocI0VJp02uok+BX7YYc6W7Tr20Eh+v2IuQ48FJRcwDplzbbDQkPq43qNGf1jNOIeTh1YWsn0BQMBcZkkgqfJKKK3N36mbBIS0KSYlwIP0VrLAgMBAAECggEAX56gySyveVe0Bg+9y2MSsX7fqxl+LRD2ZhUr3NrxQrwZcwiKa1kUCrmHcYudZkF8AGh8Kt0ao2YvJNQEujzmqd+pvOZukNYBsAiG3TtGcQDZo7VQpEERWb4uNgUpyCQgx8CrnCWrd9ZMwzS8bJFGS0UcWGXFoXQ2ixjaYc1kPx/zKmFRyesiS0ihrE1/nk/V6NVF9yakb8xAyHOici+LN1+mIQxfE7SSaNR1yJrkZQUXuuXi8rQfTz/6VOyW8LY7tkx5IPGSCp1UYY+Lq1AG1N80xJWDMTNStorR6hv031SZw9Vx/ZEFy6Jr8GxSNpLO9JQJFEMnFGc4XhqLHryoAQKBgQDlGW5GaZJfaNx8pnvn+VYu+sgxP5datYiYaDOUty7goYxm4R+ftPxwXEXTSXOFXJe8QkOeel2blcQjTyMeGjod622v/MW2BcF+dy+FAS2WOs92islENuXQo2HqHkdlMuxpuYvxAJ3JV7Ltq00CjKQXRnStXt3JMlvk+wv2sMbeywKBgQC0YLdB5B4rDcBjLuAG+yr+4lmgVIzx4O9Tr7xyXPq18skUIA8yEBFBqfkSlhU4U+IVMRq9BlUe5kDXupf57DS8srtfAW+HCl+UycS7neNGufV2g2+C0iFdv7dLS6RAQzcshnXPu1Z60VRRks6jIHwlhZ56aqE1UHCMpTg2CPP0AQKBgQDCqbcfsTikRS+D4tpJo3ztcj2ESypJ8xHbnj6l0HjOebYY/JSoWVpeBql1/GViHej4F73o/MRpHPqJngaS32oeXhrXfIpqPb3JvW/tLbEUg2ggq5CUm6jufMUH7y5u+LQUqYoU/5cSq6fndrR6xBHxjPY7Ee6VtGqMyBvEQzTXvQKBgHfj8Opy3TpwoXdLKMx7FVDk0f2nNSdwAqL1I6Q/+MQG42/k/zSfSVkDyPF5oBEYcCT1xnftRZaMJH0/INSVE1h40+GJ6r8vPeh/U6wAfZf88hIbunqRgGv3ibUaScoM4xdNJ/Ey64Amsoylr4LtjJbEAVoMlaoCFUzmZD5GJSABAoGAGLIveRatZSQZh4wfKHRBnr3Y2E5bW0spgO8t1smlhREEezA5xW/8f+2AljNDvbrjzB3Xsiwdo5Ivf4sB2Z564LZB3fSDYIYPGhaanEvBO/uCR0azzKKx7AhlYi29O5RVaqmM6MBW/iswpTraAFxUptN+7OZVVIqWw3TH2oOVnhM=
    alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuXjH2Qeokt2H3hK+rzmdd/zPC8YbucxWRXNmzQ8ZTLtHd7cGpy9LPV8XZ1Flr6/51dr5XblgOrQ8wbUitkmJE4xoCRu5iPUp6afSML3tTBeMsDVeEd6IQdIRZUy1g3ZlOm4J131TOTHxGfgOqZITYNtKYlhhdXaU6GMZ2dG7oVI+lfaKR8IFHP7cO5QwkJf3RP7FFmIf3OkDbCa/lejR+Dsop4KotNhelPOGU76C6jIDYg1n2l8KQiIt0jAzFEILlh3xye846IzlqJUu6BKRi0ixtLAC10BmrqykDJVXBMt+1If/It/KT11zsaBsYlG18PxEBNGXbfnSjMU1KvKUiQIDAQAB
    returnUrl: http://47.93.13.31/mp/alipay/wap/returnUrl
    notifyUrl: http://47.93.13.31/mp/alipay/notify