spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cctower?useUnicode=true&characterEncoding=UTF8
    username: root
    password: Cctower0000*
  redis:
    host: 47.93.13.31
    port: 6379
    password: Cctower0000*
    timeout: 1000
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 100
        max-wait: -1
  rabbitmq:
    host: 47.93.13.31
    port: 5672
    username: cctower
    password: Cctower00000*

# wx相关信息
wx:
  app-id: wx84582d8d20ac4deb
  app-secret: b25600a51d090381e02dd4b543955641
  mch-id: 1527166311
  mch-key: MQF82fY2pbWJOvGutpa7yHaK5pSgbAPK
  notify-url: https://www.cctower.cn/applet/wx-pay/pay-notify
  key-path: /usr/local/cctower/1527166311_20190406_cert/