spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cctower?useUnicode=true&characterEncoding=UTF8
    username: root
    password: Cctower0000*
  redis:
    host: 47.93.13.31
    port: 6379
    password: Cctower0000*
    timeout: 1000
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 100
        max-wait: -1
  rabbitmq:
    host: 47.93.13.31
    port: 5672
    username: cctower
    password: Cctower00000*
  activemq:
    broker-url: tcp://47.93.13.31:61616
    user: cctower
    password: Cctower00000*
  jms:
    pub-sub-domain: false     #false=Queue  true=Topic
# wx相关信息
wx:
  app-id: wx84582d8d20ac4deb
  app-secret: b25600a51d090381e02dd4b543955641
  mch-id: 1527166311
  mch-key: MQF82fY2pbWJOvGutpa7yHaK5pSgbAPK
  notify-url: https://www.cctower.cn/applet/wx-pay/pay-notify
  key-path: /usr/local/cctower/1527166311_20190406_cert/

pay:
  alipay:
    gatewayUrl: https://openapi.alipay.com/gateway.do
    appid: 2021001103674204
    appPrivateKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCOtedP1MtB6yalg7zgcodIJhxkCN7usrACB7ENK2Qsf5PiQUQn30ALGUgmN1pydsMY9UwjIRBPAJtVM6Zs+M8AeheH3z1IzwL/7QuJ88ibR7RL6MxlggNJ33N2z9kaYjZYb1rlIWdxYpObD5FQj0ZYyFfvKfJeK8tO33tNYvlXLjhO2aW6WEnUau5w7fXei+Ycq58U/hPLMUqkTpM/qK9+UmybZ6z4MvWYG9ubpdC5jQD+H4j4hM2Z8bE7uAw4RLzBn2/BYhmngS9bW/A7PZVlWSEdOzq0RH4YM7K8CWQIJD44GFz3bRvxAl/Pl+De180L8iK4qbyKdoQDJMb4yb97AgMBAAECggEADo14IAjoDTnIgBpV+WFUcEQKoxzQdvDbx+k24cvp9CuyTeEv7Qzz/+29EMCWRZPcwz/IWtC1VAkQzfhtYTFiEn9gxOc73Z/Wg3iNs6ybaVI/jXoY1cUTRsY1hQke73TSa+Q3FaR5YvOVb7t/qwJhPw53ARl68KVwnwNlFHgiSwRxdG6krMSCgxSb5roryqoJtwdWTyi9fE34ZLE0UALZyrXYmIomnDdaMaZ4FISSvoXTbtEOhHHYsD9hZo8nGUVzOJZgv/PEXlSYv0OVE3rGRTklQm1tl9jgnIatxZUjSfvp3DWUZ7yBZGFucHRBfooo6pZiTGAl+OQrdR1EXq8TkQKBgQDP99+v30C0qMZHpwwoNTCp7lc2fwP0/Sr2jtJNBTisIhsEGzWI4ZZfxJJYr6Yg3nSlsThTbSHLiJ0QkMC9zpdN4TRwJUH/8KI2FOZWckIqNWSE8ytMTsAvZsj2ymZ2HCizUMsa1oVBZeiRunj4sVG5+k2Le/Q6vq/oL5DLrvKDmQKBgQCvq6rkcvgLyDId6GjGPIj/FIJmumd/fN/1Dy4q+/4Fha10vnP7xrTbC6FZIV9dm94/dyylOdt5zyKJYUg41IfV/s9iz2XEXVADIBBiAks4URzZ7iAE3yi89gMax6gHbdUqcaWRmgh8UImW2XOQxWHvL4xsiPWeQYYC2/B47zrIMwKBgQCyfDQYRuzLoAX8PNvsLipDzXBALyaAPj9/N/g5bf/Di8nP7mI1xhY+vwAy6R0VHJbUFZMX1pOokOjr7K/ets2YY22TygYo2Kb+71T4YDt06joI+IHyjavXgsl7NR5Ww7gSnYaS1AWtqP6/A2ELX3Oav72JtqpXOIzUIu6MQOuWEQKBgQCQ2mUX6xVN4c4xiyqaC+CLNUYxnxMotLeXQuU23IMh2pCk60aIHdmTpYtuC26vqY8hlgtiUsr/LiW0UltTQSyg8HPhblLkEG2hphbcOjf8QCYiLZCJc9oLtm/o7SlItvBHB18XKIRGvcI2eSgqABg5OmP4OxcNX8o5IVKw5dL6sQKBgBVYE2lDQ4XAxSa32sYPDW1/ZTM04mhGazNPutmy+V/jaglM5iJxMJsDdv1RmP5/+hYOe8Jr/OpLiaq5RiHH+ZX7YU98Ivll473j/K/aIZQQLTQK+ZS1hmTVw1aq0EHgbKBFeWyek2GFKInRAh+r+T9OWhyxww57WRuEeJwFpxpr
    alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzCinPFUONirNq9SkDNoVmfbwtM9pO9UA+381VH+ZqqA1q70n2Y7/tTs5dUMfdJ1QPxozqAo490GlFrnnipuOCUqCYEXf+wZVp2ZWjNzddGVlhuj2GEOKb9Ips9AQIUX08AIwmooxObpu9UluPOtZNkbnWSYbRRoSe/SWpPPtNCSd8lBax7jf/HXDOyfHT+vVvBSgiPqQy+DFfWb193PVKhTFTUuUprp72NI/Gba8m54hu7USownC/uvWH9tRoZX7Wx0hGRfBj6vD9dfy4jC07i8eFX1Sfw21NKrDt+6MpM8OstyXe2q75Iuikit9jwiHdrX1A8QhKLZTde6h20OUVQIDAQAB
    returnUrl: https://www.cctower.cn/mp/alipay/wap/returnUrl
    notifyUrl: https://www.cctower.cn/mp/alipay/notify